version: "3.7"

x-test:
  &default-test
  working_dir: /home/nemo/plugin
  command: fishtape test/*.test.fish

x-build:
  &default-build
  context: .

services:
  test-on-fish-2.3:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=2.3
  test-on-fish-2.4:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=2.4
  test-on-fish-2.5:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=2.5
  test-on-fish-2.6:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=2.6
  test-on-fish-2.7:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=2.7
  test-on-fish-3.0:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=3.0
  test-on-fish-3.1:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=3.1
