version: "3.7"

x-test:
  &default-test
  working_dir: /home/nemo/plugin
  command: fishtape test/*.test.fish

x-build:
  &default-build
  context: .

services:
  test-on-fish-3.0:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=3.0
  test-on-fish-3.1:
    << : *default-test
    build:
      <<: *default-build
      args:
        - FISH_VERSION=3.1
